---
application:
  name: "freegym-api"
  project: "freegym-api"
  organization: "QoveryCommunity"
routers:
- name: "main-freegym-api"
  routes:
  - application_name: "freegym-api"
    paths:
    - "/*"
